# Basic
title: 一行和行行的故事
subtitle: 生活中的无聊杂碎
welcome_message: <a href="http://story.maple.im/2019/06/argument/">今天吵点什么</a>
# description: Vno Jekyll is a port of my Ghost theme vno.
creator: <a href="http://maple.im">Maple Yin</a>

url: "http://story.maple.im"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: orange

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    # - {title: 关于, description: about, url: 'http://story.maple.im'}
    - {title: 关于, description: about, url: 'http://story.maple.im'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
#     disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
#     weibo: onevcat
#     github: onevcat
#     twitter: onevcat
#     gplus: 107108267983477358170
#     mail: onev@onevcat.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
